name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjNhMzE3ZWEtYTcxZS00OWY5LTg3N2QtYjA5OGUzZjRjMTM4IiwidGVuYW50X2lkIjoiMjBlZmM0ZWFkMDk1ZmFhNzU1NjNmOTg3ZDFjZWJlYWM5YTM5ZDIwNTgxNTMwYzgzMDc0ZjEyMzQ0MTJhYmU3NSIsImludGVybmFsX3NlY3JldCI6IjhjMTI2NGQ5LTYwZTctNDliMy1iMzZlLThjODZkNGZlMGEwMSJ9.DE7FKVoYMw_QALQRAdzFrpVAI-0VAWHHw2d3ELz3P44"
JWT_SECRET = "nikhil"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1